### PR TITLE
Klogv2

### PR DESCRIPTION
**Pull request by wanyufe**
*Issue #, if available:*
klog v1 incompatible with eks-a go-logr/logr version
*Description of changes:*
Upgrade klog from v1 to v2 to solve compatible issue with go-logr/logr
*Testing performed:*
Unit testing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by wongni — APPROVED** [review]

**Comment by rejoshed** [comment]
/approve

But I'd like to know how this affects log output.

**Review by rejoshed — APPROVED** [review]

**Pull request merged**
